### ISSUE TITLE
Explore test kitchen

### ISSUE THREAD

**Issue by afred** [WGBH/mla-playbooks#11]
**done when** try test kitchen for testing roles

**Comment by afred** [comment]
See https://github.com/WGBH/mla-playbooks/tree/11-test-kitchen for progress.

Got stuck on getting my Vagrant box to download ansible in order to run `ansible-playbook`.

Here is the output I was getting when running `kitchen converge`:

```
       Installing ansible, will try to determine platform os
       which: no ansible in (/usr/local/bin:/bin:/usr/bin)
       bash: line 2: [: too many arguments
       which: no ansible in (/usr/local/bin:/bin:/usr/bin)
       Retrieving https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
       curl: (6) Couldn't resolve host 'download.fedoraproject.org'
       error: skipping https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm - transfer failed
       Loaded plugins: fastestmirror
       Determining fastest mirrors
       Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os error was
       14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
       Error: Cannot find a valid baseurl for repo: base
       Loaded plugins: fastestmirror
       Loading mirror speeds from cached hostfile
       Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os error was
       14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
       Error: Cannot find a valid baseurl for repo: base
-----> Installing Chef Omnibus to install busser to run tests
       downloading https://www.getchef.com/chef/install.sh
         to file /tmp/install.sh
       trying wget...
       trying curl...

       curl: (6) Couldn't resolve host 'www.getchef.com'
       trying python...
       Traceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
           return _opener.open(url, data, timeout)
         File "/usr/lib64/python2.6/urllib2.py", line 391, in open
           response = self._open(req, data)
         File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
           '_open', req)
         File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
           result = func(*args)
         File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
           return self.do_open(httplib.HTTPSConnection, req)
         File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
           raise URLError(err)
       urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
>>>>>> wget, curl, fetch, perl or python not found on this instance.
       Transferring files to <default-centos-65>
       Going to invoke ansible-playbook with: ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vvv       /tmp/kitchen/default.yml
       sudo: ansible-playbook: command not found
>>>>>> Converge failed on instance <default-centos-65>.
>>>>>> Please see .kitchen/logs/default-centos-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E ansible-playbook --inventory-file=/tmp/kitchen/hosts -c local -M /tmp/kitchen/modules -vvv       /tmp/kitchen/default.yml]
>>>>>> ----------------------
```

**Comment by afred** [comment]
tabling testing for now, see #15
